-- DEMOSVITA MVP - CATÁLOGO FUNDACIONAL DE 15 MISIONES
-- Ejecutar desde Supabase > SQL Editor una vez desplegado el código web.
-- Es idempotente: se puede volver a ejecutar sin duplicar misiones.

begin;

alter table public.missions
  add column if not exists feedback_prompt text,
  add column if not exists sort_order integer not null default 999;

create index if not exists missions_active_sort_idx
  on public.missions (is_active, sort_order, code);

insert into public.missions (
  code,
  slug,
  title,
  tagline,
  description,
  category,
  difficulty,
  xp,
  conditions,
  feedback_prompt,
  image_url,
  sort_order,
  is_active,
  published_at
)
values
  (
    'M01_HALAGO_HONESTO',
    'el-halago-honesto',
    'El halago honesto',
    'El que se guarda un halago, se queda con algo que no es suyo.',
    'Dile a un desconocido algo genuinamente positivo que hayas notado. Sin motivo. No hace falta que sea perfecto, solo honesto.',
    'Conecta',
    'Difícil',
    150,
    '["A un desconocido", "En un lugar público", "Que derive en al menos 5 minutos de conversación"]'::jsonb,
    'Texto: qué dijiste y cómo reaccionó.',
    '/assets/misiones/halago-portada.png',
    6,
    true,
    now()
  ),
  (
    'M02_COMERCIANTE_LOCAL',
    'el-comerciante-local',
    'El comerciante local',
    null,
    'Habla con quien atiende una tienda de tu barrio. Pregúntale algo sobre su oficio.',
    'Explora',
    'Fácil',
    70,
    '["Hablar con quien atiende una tienda del barrio", "Preguntarle algo sobre su oficio"]'::jsonb,
    'Texto: qué te contó.',
    null,
    1,
    true,
    now()
  ),
  (
    'M03_ADOPTA_UN_LUGAR',
    'adopta-un-lugar',
    'Adopta un lugar',
    null,
    'Ve al mismo café, parque o librería 3 veces esta semana, a la misma hora.',
    'Explora',
    'Media',
    120,
    '["Visitar el mismo lugar 3 veces en una semana", "Ir a la misma hora en cada visita"]'::jsonb,
    'Una foto del lugar por visita y un texto final.',
    null,
    2,
    true,
    now()
  ),
  (
    'M04_EVENTO_QUE_NUNCA_HARIAS',
    'el-evento-que-nunca-harias',
    'El evento que nunca harías',
    null,
    'Apúntate solo o sola a una actividad grupal de tu barrio que nunca hayas probado.',
    'Explora',
    'Difícil',
    160,
    '["Inscribirte sin compañía", "Elegir una actividad grupal del barrio", "Probar algo que nunca hayas hecho"]'::jsonb,
    'Texto obligatorio y foto opcional.',
    null,
    3,
    true,
    now()
  ),
  (
    'M05_RECOMENDACION_DESCONOCIDO',
    'la-recomendacion-de-un-desconocido',
    'La recomendación de un desconocido',
    null,
    'Pide a alguien que no conoces que te recomiende un libro, un sitio o una canción.',
    'Conecta',
    'Fácil',
    70,
    '["Pedir la recomendación a alguien que no conoces", "Elegir un libro, un sitio o una canción"]'::jsonb,
    'Texto: qué te recomendó.',
    null,
    4,
    true,
    now()
  ),
  (
    'M06_DIEZ_MINUTOS_SIN_SALIDA',
    'diez-minutos-sin-salida',
    'Diez minutos sin salida',
    null,
    'Habla con un desconocido al menos 10 minutos, sin pedir nada concreto.',
    'Conecta',
    'Media',
    100,
    '["Hablar con una persona desconocida", "Mantener la conversación al menos 10 minutos", "No pedir nada concreto"]'::jsonb,
    'Texto: de qué hablasteis.',
    null,
    5,
    true,
    now()
  ),
  (
    'M07_CAFE_SIN_PANTALLA',
    'el-cafe-sin-pantalla',
    'El café sin pantalla',
    null,
    'Pasa 30 minutos sin mirar el móvil.',
    'Contempla',
    'Fácil',
    70,
    '["Permanecer 30 minutos sin mirar el móvil"]'::jsonb,
    'Texto: qué notaste y foto opcional del lugar.',
    null,
    7,
    true,
    now()
  ),
  (
    'M08_MODO_AVION_COMPARTIDO',
    'modo-avion-compartido',
    'Modo avión compartido',
    null,
    'Pasa 3 horas en modo avión haciendo algo con alguien.',
    'Contempla',
    'Media',
    110,
    '["Activar el modo avión durante 3 horas", "Compartir ese tiempo con otra persona"]'::jsonb,
    'Texto: qué hicisteis.',
    null,
    8,
    true,
    now()
  ),
  (
    'M09_DIA_ENTERO_SIN_REDES',
    'el-dia-entero',
    'El día entero',
    null,
    'Pasa 24 horas sin redes sociales.',
    'Contempla',
    'Difícil',
    160,
    '["Completar 24 horas sin utilizar redes sociales"]'::jsonb,
    'Texto reflexivo al final del día.',
    null,
    9,
    true,
    now()
  ),
  (
    'M10_LIBRERIA_AL_AZAR',
    'libreria-al-azar',
    'Librería al azar',
    null,
    'Elige un libro solo por su portada, sin leer la sinopsis.',
    'Descubre',
    'Fácil',
    70,
    '["Elegir el libro únicamente por la portada", "No leer la sinopsis antes de elegir"]'::jsonb,
    'Foto del libro y texto: por qué elegiste esa portada.',
    null,
    10,
    true,
    now()
  ),
  (
    'M11_MANOS_OCUPADAS',
    'manos-ocupadas',
    'Manos ocupadas',
    null,
    'Dedica 30 minutos a algo manual sin pantallas: dibujar, cocinar, reparar o cualquier otra actividad.',
    'Descubre',
    'Media',
    110,
    '["Dedicar al menos 30 minutos", "Realizar una actividad manual", "No utilizar pantallas"]'::jsonb,
    'Foto del resultado.',
    null,
    11,
    true,
    now()
  ),
  (
    'M12_APRENDE_DE_UN_EXTRANO',
    'aprende-de-un-extrano',
    'Aprende de un extraño',
    null,
    'Pide a alguien que te enseñe durante 15 minutos algo que no sabes hacer.',
    'Descubre',
    'Difícil',
    160,
    '["Pedir ayuda a alguien que no conoces", "Aprender algo nuevo durante al menos 15 minutos"]'::jsonb,
    'Texto: qué aprendiste y de quién.',
    null,
    12,
    true,
    now()
  ),
  (
    'M13_PIDE_SIN_MIEDO',
    'pide-sin-miedo',
    'Pide sin miedo',
    null,
    'Pide algo que normalmente no pedirías: un descuento, cambiar de mesa o que te repitan algo.',
    'Supera',
    'Fácil',
    70,
    '["Pedir algo que normalmente no pedirías"]'::jsonb,
    'Texto breve: qué pediste y qué pasó.',
    null,
    13,
    true,
    now()
  ),
  (
    'M14_NO_QUE_SE_CONVIERTE_EN_SI',
    'el-no-que-se-convierte-en-si',
    'El no que se convierte en sí',
    null,
    'Acepta esta semana algo a lo que sueles decir que no.',
    'Supera',
    'Media',
    110,
    '["Aceptar durante esta semana algo a lo que sueles decir que no"]'::jsonb,
    'Texto: qué aceptaste y cómo fue.',
    null,
    14,
    true,
    now()
  ),
  (
    'M15_MOMENTO_INCOMODO',
    'el-momento-incomodo',
    'El momento incómodo',
    null,
    'Haz algo en público que te dé vergüenza —cantar, bailar o hablar en grupo— durante al menos 10 segundos.',
    'Supera',
    'Difícil',
    160,
    '["Hacerlo en público", "Elegir algo que te dé vergüenza", "Mantenerlo al menos 10 segundos"]'::jsonb,
    'Marca «Lo hice» y añade un texto opcional.',
    null,
    15,
    true,
    now()
  )
on conflict (code) do update set
  slug = excluded.slug,
  title = excluded.title,
  tagline = excluded.tagline,
  description = excluded.description,
  category = excluded.category,
  difficulty = excluded.difficulty,
  xp = excluded.xp,
  conditions = excluded.conditions,
  feedback_prompt = excluded.feedback_prompt,
  image_url = coalesce(public.missions.image_url, excluded.image_url),
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  published_at = coalesce(public.missions.published_at, excluded.published_at),
  updated_at = now();

commit;

-- Deben aparecer 15 filas activas en este orden.
select
  sort_order,
  code,
  title,
  category,
  difficulty,
  xp,
  feedback_prompt,
  image_url
from public.missions
where is_active = true
order by sort_order, code;
