-- DEMOSVITA MVP - FORMULARIOS DE FEEDBACK DINÁMICOS
-- Añade un esquema tipado a cada misión y almacenamiento flexible a los reportes.
-- Es idempotente y no modifica ni elimina respuestas anteriores.

begin;

alter table public.missions
  add column if not exists feedback_schema jsonb not null default '[]'::jsonb;

alter table public.mission_reports
  add column if not exists answers jsonb not null default '{}'::jsonb;

with mission_schemas (code, feedback_schema) as (
values
  ('M02_COMERCIANTE_LOCAL', '[{"key":"q1","label":"¿Dónde lo hiciste?","required":true,"type":"text"},{"key":"photo","label":"Foto del sitio (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué le preguntaste?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Qué te contó que no esperabas?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste al entrar y al salir?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M03_ADOPTA_UN_LUGAR', '[{"key":"q1","label":"¿Qué lugar elegiste?","required":true,"type":"textarea","rows":3},{"key":"photo","label":"Foto del lugar (opcional, una por visita)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Notó alguien que volvías?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Qué cambió entre la primera y la tercera vez?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Lo convertirás en costumbre?","required":true,"type":"select","options":["Sí","No","No lo sé todavía"]}]'::jsonb),
  ('M04_EVENTO_QUE_NUNCA_HARIAS', '[{"key":"q1","label":"¿Qué actividad elegiste y dónde?","required":true,"type":"textarea","rows":3},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué casi te hace no ir?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Cómo te recibieron?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Fue más fácil o más difícil de lo que esperabas?","required":true,"type":"select","options":["Mucho más fácil","Algo más fácil","Como esperaba","Algo más difícil","Mucho más difícil"]}]'::jsonb),
  ('M05_RECOMENDACION_DESCONOCIDO', '[{"key":"q1","label":"¿Dónde lo hiciste?","required":true,"type":"text"},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué te recomendó?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Te atreverías a seguirla al pie de la letra?","required":true,"type":"select","options":["Sí","No","No lo sé todavía"]},{"key":"q5","label":"¿Cómo reaccionó al pedírselo?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M06_DIEZ_MINUTOS_SIN_SALIDA', '[{"key":"q1","label":"¿Dónde y con quién?","required":true,"type":"text"},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿De qué hablasteis?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Cómo terminó la conversación?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste antes de acercarte y después de despedirte?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M01_HALAGO_HONESTO', '[{"key":"q1","label":"¿Dónde lo hiciste?","required":true,"type":"text"},{"key":"photo","label":"Foto del sitio (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué le dijiste exactamente?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Cómo reaccionó?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Fue más fácil o más difícil de lo que esperabas?","required":true,"type":"select","options":["Mucho más fácil","Algo más fácil","Como esperaba","Algo más difícil","Mucho más difícil"]},{"key":"q6","label":"¿Cómo te sentiste antes y después?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M07_CAFE_SIN_PANTALLA', '[{"key":"q1","label":"¿Dónde lo hiciste?","required":true,"type":"text"},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué notaste que normalmente se te escapa?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Cuántas veces sentiste el impulso de mirar el móvil?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste al terminar?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M08_MODO_AVION_COMPARTIDO', '[{"key":"q1","label":"¿Con quién y haciendo qué?","required":true,"type":"text"},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué hicisteis con el tiempo de más?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿La otra persona lo notó?","required":true,"type":"select","options":["Sí","No","No lo sé todavía"]},{"key":"q5","label":"¿Cómo te sentiste antes y después?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M09_DIA_ENTERO_SIN_REDES', '[{"key":"q1","label":"¿Qué día lo hiciste?","required":true,"type":"text"},{"key":"photo","label":"Foto (opcional, del momento que más recuerdas de ese día)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué hiciste con el tiempo que ganaste?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿En qué momento te costó más?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste al final del día?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M10_LIBRERIA_AL_AZAR', '[{"key":"q1","label":"¿Qué librería?","required":true,"type":"text"},{"key":"photo","label":"Foto del libro (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué portada te llamó y por qué?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Ya sabías algo de ese libro?","required":true,"type":"select","options":["Sí","No","No lo sé todavía"]},{"key":"q5","label":"¿Lo leerás de verdad?","required":true,"type":"select","options":["Sí","No","No lo sé todavía"]}]'::jsonb),
  ('M11_MANOS_OCUPADAS', '[{"key":"q1","label":"¿Qué hiciste?","required":true,"type":"textarea","rows":3},{"key":"photo","label":"Foto del resultado (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Cuánto tiempo hacía que no hacías algo así?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Qué tal salió?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste mientras lo hacías?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M12_APRENDE_DE_UN_EXTRANO', '[{"key":"q1","label":"¿Qué aprendiste y de quién?","required":true,"type":"textarea","rows":3},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Cómo le pediste que te enseñara?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Qué fue lo más difícil de aprenderlo?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste como principiante?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M13_PIDE_SIN_MIEDO', '[{"key":"q1","label":"¿Qué pediste y dónde?","required":true,"type":"textarea","rows":3},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Qué te dijeron?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Qué te frenaba normalmente para pedirlo?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste al hacerlo?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M14_NO_QUE_SE_CONVIERTE_EN_SI', '[{"key":"q1","label":"¿Qué aceptaste?","required":true,"type":"textarea","rows":3},{"key":"photo","label":"Foto (opcional)","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Por qué sueles decir que no a esto normalmente?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Qué tal fue?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste al decir que sí?","required":true,"type":"textarea","rows":3}]'::jsonb),
  ('M15_MOMENTO_INCOMODO', '[{"key":"q1","label":"¿Qué hiciste y dónde?","required":true,"type":"textarea","rows":3},{"key":"q2_confirmed","label":"Confirmo que completé la acción indicada en la misión.","type":"checkbox","required":true},{"key":"photo","label":"foto opcional","type":"photo","required":false,"help":"Evita fotografiar a personas sin su permiso. Máximo 4 MB."},{"key":"q3","label":"¿Cómo reaccionó la gente alrededor?","required":true,"type":"textarea","rows":3},{"key":"q4","label":"¿Qué fue lo más difícil, el momento antes o durante?","required":true,"type":"textarea","rows":3},{"key":"q5","label":"¿Cómo te sentiste después?","required":true,"type":"textarea","rows":3}]'::jsonb)
)
update public.missions as mission
set
  feedback_schema = schema.feedback_schema,
  updated_at = now()
from mission_schemas as schema
where mission.code = schema.code;

commit;

-- Deben aparecer 15 misiones con entre 5 y 6 campos específicos.
select
  code,
  title,
  jsonb_array_length(feedback_schema) as campos_feedback
from public.missions
where is_active = true
order by sort_order, code;
